server:
    port: 8888

app:
  api-prefix: /api

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: kpi
                  uri: http://localhost:8081
                  predicates:
                      - Path=${app.api-prefix}/kpi/**
                  filters:
                    - StripPrefix=1