version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=khangttcnpm2024
      - POSTGRES_DB=KPI

  dockerize:
    container_name: dockerize_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/KPI
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=khangttcnpm2024
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db